# This workflow will do a clean install of node dependencies and run the linter

name: Run linter

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc

    - run: npm ci

    - run: npm run lint
