# This workflow will do a clean install of node dependencies and run the linter

name: Run linter

on: [pull_request, push]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 20
      uses: actions/setup-node@v1
      with:
        node-version: 20

    - run: npm ci

    - run: npm run lint
